"""
Figma 直连流程图（MCP 驱动）

完整 9 节点流水线，与 Traditional 流程的核心区别：
  Traditional：用户描述 → 多步骤 AI 分析 → 逐文件生成代码 → 组装
  Figma：设计稿 URL → MCP 一次性拿到代码 → 后处理拆解 → 重构为组件

节点职责：
  figmaInputNode      调用 Figma Desktop MCP Server 获取整页 TSX 代码（耗时约 1-3 分钟）
  imageDownloadNode   提取代码中的临时图片 URL，下载并上传到 OSS 替换为永久链接
  astParserNode       正则解析 TSX，提取顶层组件结构（确定性，无 AI）
  blockExtractNode    从 Tailwind 类名/内联 style 提取每个块的坐标（top/left/width/height）
  geometryGroupNode   按 Y 轴自适应聚类，将相近元素合并为一个 Section
  sectionNamingNode   AI 语义命名：根据文本/图片内容给每个 Section 起组件名（轻量 AI）
  componentGenNode    AI 组件生成：并行为每个 Section 生成独立的 React 组件（重量 AI）
  assemblyNode        将所有组件组装成 Sandpack 格式的文件集合（确定性）
  figmaPostProcessNode AST 级别修复（对象渲染/安全访问等问题）（确定性）
  figmaCompileCheckNode 临时 Vite 项目真实编译校验，失败则中断返回错误
"""
from typing import Any, Dict, List, Optional

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# Input Phase
from agents.flows.figma_direct.input.nodes.figma_input_node import figma_input_node
from agents.flows.figma_direct.input.nodes.image_download_node import image_download_node

# Parsing Phase (deterministic, no AI)
from agents.flows.figma_direct.parsing.nodes.ast_parser_node import ast_parser_node
from agents.flows.figma_direct.parsing.nodes.block_extract_node import block_extract_node
from agents.flows.figma_direct.parsing.nodes.geometry_group_node import geometry_group_node

# Refactoring Phase (AI)
from agents.flows.figma_direct.refactoring.nodes.section_naming_node import section_naming_node
from agents.flows.figma_direct.refactoring.nodes.component_gen_node import component_gen_node

# Assembly Phase (deterministic, no AI)
from agents.flows.figma_direct.assembly.nodes.assembly_node import assembly_node
from agents.flows.figma_direct.assembly.nodes.figma_post_process_node import figma_post_process_node
from agents.flows.traditional.assembly.nodes.compile_check_node import compile_check_node
from agents.flows.traditional.assembly.nodes.compile_fix_router import (
    route_after_compile_check,
)
from agents.flows.traditional.assembly.nodes.debug_fix_node import debug_fix_node

checkpointer = MemorySaver()


class FigmaGraphState(TypedDict, total=False):
    """Figma direct flow graph state."""

    # --- Common input ---

    # Chat history for preserving user context
    messages: List[Any]
    conversationSummary: Optional[str]

    # Figma design URL - main input for Figma flow
    figmaUrl: Optional[str]

    # Optional user text description for supplementary context
    textPrompt: Optional[str]

    # Mock config
    mockConfig: Optional[Dict[str, Any]]

    # --- Input Phase ---

    # Raw frontend code string generated by MCP Server
    figmaCode: Optional[str]

    # Character count of the raw code
    codeLength: Optional[int]

    # Total line count of the raw code
    lineCount: Optional[int]

    # --- Parsing Phase ---

    # AST parser output: entry component, top-level JSX, global assets, helper components
    parsedBlocks: Optional[List[Dict[str, Any]]]

    # Layout block extracts: blocks with coordinates and page height
    blockExtracts: Optional[List[Dict[str, Any]]]

    # Geometry group result: sections split by spatial position
    geometryGroups: Optional[List[Dict[str, Any]]]

    # --- Refactoring Phase ---

    # Named sections: semantic component names for each section
    namedSections: Optional[List[Dict[str, Any]]]

    # AI-generated component files: one per section
    figmaComponents: Optional[List[Dict[str, Any]]]

    # --- Assembly / Output Phase ---

    # Final Sandpack file collection with content and stats
    files: Optional[Dict[str, Any]]


def build_figma_agent():
    """Build and compile the Figma direct flow agent."""
    graph = StateGraph(FigmaGraphState)

    # Register nodes

    # Input Phase (get code + image processing)
    graph.add_node("figmaInputNode", figma_input_node)
    graph.add_node("imageDownloadNode", image_download_node)

    # Parsing Phase (deterministic, no AI)
    graph.add_node("astParserNode", ast_parser_node)
    graph.add_node("blockExtractNode", block_extract_node)
    graph.add_node("geometryGroupNode", geometry_group_node)

    # Refactoring Phase (AI)
    graph.add_node("sectionNamingNode", section_naming_node)
    graph.add_node("componentGenNode", component_gen_node)

    # Assembly Phase (deterministic, no AI)
    graph.add_node("assemblyNode", assembly_node)
    graph.add_node("figmaPostProcessNode", figma_post_process_node)
    graph.add_node("figmaCompileCheckNode", compile_check_node)
    graph.add_node("figmaDebugFixNode", debug_fix_node)

    # Orchestration flow
    graph.add_edge(START, "figmaInputNode")
    graph.add_edge("figmaInputNode", "imageDownloadNode")
    graph.add_edge("imageDownloadNode", "astParserNode")
    graph.add_edge("astParserNode", "blockExtractNode")
    graph.add_edge("blockExtractNode", "geometryGroupNode")
    graph.add_edge("geometryGroupNode", "sectionNamingNode")
    graph.add_edge("sectionNamingNode", "componentGenNode")
    graph.add_edge("componentGenNode", "assemblyNode")
    graph.add_edge("assemblyNode", "figmaPostProcessNode")
    graph.add_edge("figmaPostProcessNode", "figmaCompileCheckNode")
    graph.add_conditional_edges(
        "figmaCompileCheckNode",
        route_after_compile_check,
        {"debugFixNode": "figmaDebugFixNode", END: END},
    )
    graph.add_edge("figmaDebugFixNode", "figmaCompileCheckNode")

    return graph.compile(checkpointer=checkpointer)
